config/routes.rb
Rails.application.routes.draw do
  root 'staticpages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  delete '/logout', to:'sessions#destroy' 
  resources :sessions
  resources :users
  resources :relationships,only:[:create,:destroy]
  resources :categories

  resources :lessons,only:[:create, :show] do
    resources :answers
  end
  
  namespace :admin do
    get'/home', to:'users#home'
    resources :users
    resources :categories do
      resources :words
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :action,polymorphic: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :lesson
  belongs_to :word
  belongs_to :choice
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  has_many :words, dependent: :destroy
  has_many :lessons,dependent: :destroy
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :word
  has_many :answer,dependent: :destroy
  validates :content, presence: true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :words, through: :answers
  has_many :choices, through: :answers
  has_one :activity,as: :action,dependent: :destroy


  def lesson_results
    choices.where(isCorrect: true).count
  end

  def next_word
    (category.words - words).first
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower ,class_name: "User"
  belongs_to :followed ,class_name: "User"
  validates :follower_id,presence: true
  validates :followed_id,presence: true
  has_one :activity,as: :action,dependent: :destroy

  after_create :relationship_activity

  private
  def relationship_activity
    create_activity(user: follower)
  end
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  #filter method to transform email to small case before saving to db 
  before_save {email.downcase!}

  validates :name, presence: true, length: {maximum:50 }
  # REGEX = Reguuler Expression
  # To validate correct email structure
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum:50 },
                                    format: {with: EMAIL_REGEX},
                                    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password,length:{minimum:6}, allow_nil:true

  has_many :active_relationships,class_name:"Relationship",
  foreign_key:"follower_id",
  dependent: :destroy

  has_many :passive_relationships,class_name:"Relationship",
  foreign_key:"followed_id",
  dependent: :destroy

  has_many :following,through: :active_relationships, source: :followed
  has_many :followers,through: :active_relationships, source: :follower
  has_many :lessons,dependent: :destroy
  has_many :activities,dependent: :destroy
  has_many :categories, through: :lessons

  #follow a user
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end
  #Unfollows a user
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  #returns ture if the current user is following the other user.
  def following? (other_user)
    following.include?(other_user)
  end

  def lesson_taken(category_id)
    lesson = lessons.find_by(category_id: category_id)
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :choices, dependent: :destroy
  has_many :answer,dependent: :destroy
  validate :has_one_correct_answer
  accepts_nested_attributes_for :choices
  validates :choices, presence: true
  validates :content, presence: true
  validate :has_unique_choice

  def has_one_correct_answer
    if choices.select{|choice| choice.isCorrect? }.count !=1
      return errors.add :base,"Must have one correct choice"
    end
  end

  def has_unique_choice
    @uniq_choices = choices.uniq{|choice| choice.content}.length
    if @uniq_choices < choices.length
      return errors.add :base,"Must have uniqe choice"
    end
  end

  def correct_answer
    choices.find_by(isCorrect:true).try(:content)
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  def new
    @category = Category.new
	end

	def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_url
    else
      render 'new'
    end
	end

	def index
		@categories = Category.paginate(page: params[:page],per_page: 10)
  end

  def show
    @category = Category.find(params[:id])
  end

	def edit
		@category = Category.find(params[:id])
	end
	def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_categories_url
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    flash[:info] = "Successflly Removed category"
    @category.destroy
    redirect_to admin_categories_url
  end
	
	private
    def category_params
      params.require(:category).permit(:title,:description)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.paginate(page: params[:page],per_page: 6)
    @status = params[:status]
    if @status == "1"
      @categories = current_user.categories.paginate(page: params[:page],per_page: 6)
    elsif @status == "0"
      @categories = @categories.where.not(id: current_user.category_ids).paginate(page: params[:page],per_page: 6)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page],per_page: 10)
  end

  def show
    @user = User.find(params[:id])
    @activities = @user.activities.paginate(page: params[:page],per_page: 5)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def dashboard_feeds
    @user = User.find(params[:id])
    @activities = @user.activities.paginate(page: params[:page],per_page: 5)
  end
  
  private
    def user_params
      params.require(:user).permit(:name,:email,:password,
      :password_confirmation)
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
      session[:user_id] = user.id
  end

    # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    #Generate hex token
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name)
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin,@category] do |f|%>
    <div class="custom-new-padding">
        <%= render 'shared/error_messages',object: f.object %>
        <div class="form-group">
            <%= f.label :title %>
            <div class="text">
                <%= f.text_field :title,class: 'form-control'%>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control'%>
        </div>
        <%= f.submit "submit", class: 'btn btn-outline-danger btn-block create create_botton category-btn'%>
    </div>
<% end %>

app/views/admin/categories/edit.html.erb
<div class="category_top">
    <h1>Edit Category</h1>
    <%= render 'form' %> 
</div>

app/views/admin/categories/index.html.erb
<div class="category_top">
    <h1>Administer Categories</h1>
    <%= link_to "new category",new_admin_category_path,class: "btn btn-outline-danger category_margin category_new" %>
</div>
<div class="table_margin">
    <table class="table">
        <thead>
    		<tr>
      			<th scope="col">Title</th>
      			<th scope="col">Description</th>
      			<th scope="col">Settings</th>
    		</tr>
  		</thead>

		<% @categories.each do |category| %>
  			<tbody>
    			<tr>
					<td><%= link_to category.title,admin_category_words_path(category.id), class:"title_color" %></td>
					<td><%=category.description%></td>
					<td><%= link_to 'edit',edit_admin_category_path(category),class:"btn btn-outline-success btn-sm float-r" %> / <%= link_to 'Delete',admin_category_path(category.id),class:"btn btn-outline-danger btn-sm float-r",method: :delete %> </td>
    			</tr>
  			</tbody>
		<% end %>
	</table>
	<div class="paginate text-center">
    	<%= will_paginate %>
	</div>
</div>

app/views/admin/categories/new.html.erb
<div class="category_top">
    <h1>New Category</h1>
    <%= render 'form' %>
</div>

app/views/categories/index.html.erb
<div class="category_top">
    <h1>Categories</h1>
</div>
<div class="filter_btn">
    <%=link_to"ALL",categories_path, class: "btn btn-outline-primary"%>
    <%=link_to"Learned",categories_path(status: "1"), class: "btn btn-outline-info"%>
    <%=link_to"Not Learned",categories_path(status: "0"), class: "btn btn-outline-secondary"%>
</div>
<div class="lesson_body">
    <div class="row">
        <% @categories.each do |category| %>
            <div class="col-sm-6">
                <div class="card card-setting">
                    <div class="card-body">
                        <%= category.title %> [<%= category.words.count%>]
                        <hr>    
                        <%= category.description%>
                        <br>
                        <% lesson =current_user.lesson_taken(category.id) %>

                        <% if lesson.nil?%>
                            <%=link_to "Start lesson", lessons_path(category_id: category.id),class:"btn btn-outline-danger btn-sm start-btn",method: :post %>
                        <% else %>
                            <%=link_to "Show result", lesson_path(lesson.category.id), class:"btn btn-outline-primary result-btn"%>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>
<div class="paginate text-center lessons_paginate">
    <%= will_paginate %>
</div>