config/routes.rb
Rails.application.routes.draw do
  root 'staticpages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  delete '/logout', to:'sessions#destroy' 
  resources :sessions
  resources :users
  resources :relationships,only:[:create,:destroy]
  resources :categories

  resources :lessons,only:[:create, :show] do
    resources :answers
  end
  
  namespace :admin do
    get'/home', to:'users#home'
    resources :users
    resources :categories do
      resources :words
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :action,polymorphic: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :lesson
  belongs_to :word
  belongs_to :choice
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  has_many :words, dependent: :destroy
  has_many :lessons,dependent: :destroy
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :word
  has_many :answer,dependent: :destroy
  validates :content, presence: true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :words, through: :answers
  has_many :choices, through: :answers
  has_one :activity,as: :action,dependent: :destroy


  def lesson_results
    choices.where(isCorrect: true).count
  end

  def next_word
    (category.words - words).first
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower ,class_name: "User"
  belongs_to :followed ,class_name: "User"
  validates :follower_id,presence: true
  validates :followed_id,presence: true
  has_one :activity,as: :action,dependent: :destroy

  after_create :relationship_activity

  private
  def relationship_activity
    create_activity(user: follower)
  end
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  #filter method to transform email to small case before saving to db 
  before_save {email.downcase!}

  validates :name, presence: true, length: {maximum:50 }
  # REGEX = Reguuler Expression
  # To validate correct email structure
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum:50 },
                                    format: {with: EMAIL_REGEX},
                                    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password,length:{minimum:6}, allow_nil:true

  has_many :active_relationships,class_name:"Relationship",
  foreign_key:"follower_id",
  dependent: :destroy

  has_many :passive_relationships,class_name:"Relationship",
  foreign_key:"followed_id",
  dependent: :destroy

  has_many :following,through: :active_relationships, source: :followed
  has_many :followers,through: :active_relationships, source: :follower
  has_many :lessons,dependent: :destroy
  has_many :activities,dependent: :destroy
  has_many :categories, through: :lessons

  #follow a user
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end
  #Unfollows a user
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  #returns ture if the current user is following the other user.
  def following? (other_user)
    following.include?(other_user)
  end

  def lesson_taken(category_id)
    lesson = lessons.find_by(category_id: category_id)
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :choices, dependent: :destroy
  has_many :answer,dependent: :destroy
  validate :has_one_correct_answer
  accepts_nested_attributes_for :choices
  validates :choices, presence: true
  validates :content, presence: true
  validate :has_unique_choice

  def has_one_correct_answer
    if choices.select{|choice| choice.isCorrect? }.count !=1
      return errors.add :base,"Must have one correct choice"
    end
  end

  def has_unique_choice
    @uniq_choices = choices.uniq{|choice| choice.content}.length
    if @uniq_choices < choices.length
      return errors.add :base,"Must have uniqe choice"
    end
  end

  def correct_answer
    choices.find_by(isCorrect:true).try(:content)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def home
        
  end

  def index
    @users = User.paginate(page: params[:page],per_page: 10)
  end

  def destroy
    @user = User.find(params[:id])
    @user.update(admin: false)
    redirect_to admin_users_url
	end
	
	def update
		@user = User.find(params[:id])
    @user.update(admin: true)
    redirect_to admin_users_url
  end
		
  private
    def user_params
      params.require(:user).permit(:name,:email,:password,
      :password_confirmation)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page],per_page: 10)
  end

  def show
    @user = User.find(params[:id])
    @activities = @user.activities.paginate(page: params[:page],per_page: 5)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def dashboard_feeds
    @user = User.find(params[:id])
    @activities = @user.activities.paginate(page: params[:page],per_page: 5)
  end
  
  private
    def user_params
      params.require(:user).permit(:name,:email,:password,
      :password_confirmation)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def gravatar_for(user)
    Generate hex token
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
      session[:user_id] = user.id
  end

    # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    #Generate hex token
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name)
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/admin/users/category.html.erb
<div class="category_top">
    <h1>Administer Categories</h1>
    <%= link_to "new category","#",class: "btn btn-outline-danger category_margin category_new" %>
</div>
<div class="table_margin">
    <table class="table">
        <thead>
    		<tr>
      			<th scope="col">#</th>
      			<th scope="col">First</th>
      			<th scope="col">Last</th>
      			<th scope="col">Handle</th>
    		</tr>
  		</thead>
  		<tbody>
    		<tr>
				<th scope="row">1</th>
				<td>Mark</td>
				<td>Otto</td>
				<td>@mdo</td>
    		</tr>
			<tr>
				<th scope="row">2</th>
				<td>Jacob</td>
				<td>Thornton</td>
				<td>@fat</td>
			</tr>
			<tr>
				<th scope="row">3</th>
				<td>Larry</td>
				<td>the Bird</td>
				<td>@twitter</td>
			</tr>
  		</tbody>
	</table>
</div>

app/views/admin/users/home.html.erb
<h1 class="admintext">Administration</h1>
<div class="button">
    <div class="users_botton">
        <%= link_to "users",admin_users_path, class: "btn btn-outline-danger users_botton_margin" %>
        <h4>You can add or remove the administ-ration to users.</h4>
    </div>
    <div>
        <%= link_to "category",admin_categories_path,class: "btn btn-outline-danger category_margin" %>
        <h4>You can change the categories, desc-riptions, words, answers and choices.</h4>
    </div>
</div>

app/views/admin/users/index.html.erb
<h1 class="text-center mb-3">Users</h1>

<div class="paginate text-center">
    <%= will_paginate %>
</div>

<div class= "row bottom">
    <% @users.each do |user| %>
        <div class="col-6">
            <div class="media mb-3">
                <%= gravatar_for(user) %>
                <div class="media-body">
                    <h5 class="pt-2 font-weight-bold"><%= link_to user.name, user %> </h5>
                </div>
                <% if user.admin? %>
                    <%= link_to 'Delete',admin_user_path(user),method: :delete,
                    class:"btn btn-outline-danger btn-sm float-r" %>    
                <% else %>
                    <%= link_to 'add',admin_user_path(user),method: :patch,
                    class:"btn btn-outline-success btn-sm float-r add_botton"%>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f|%>
    <div class="container custom-padding">
        <%= render 'shared/error_messages',object: f.object %>
        <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name,class: 'form-control'%>
        </div>

        <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control'%>
        </div>
        <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control'%>
        </div>
        <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control'%>
        </div>
        <%= f.submit "Create a new account", class: 'btn btn-outline-danger btn-block create_botton'%>
    </div>
<% end %>

app/views/users/dashboard_feeds.html.erb
<div class="row mt-4">
    <div class="col-3 text-center">
       <div class="media-body userprofile ml-3">
        	<%= gravatar_for current_user %>
        	<h4><%= current_user.name %></h4>
        	<h5><%= current_user.email %></h5>
    	</div>

        <div class="col-12 text center">
            <div class="row">
                <div class="col-6">
                    <h3><%= current_user.active_relationships.count %></h3>
                    following
                </div>
                <div class="col-6">
                    <h3><%= current_user.passive_relationships.count %></h3>
                    followers
                </div>
            </div>
        </div>
    </div>
    <div class="col-9">
       <div class="card activity feed_paginate">
            <div class="card-header">
                Activities
            </div>
            <div class="card-body">
                <%= render 'shared/feed', locals: {activities: @activities} %>
                <div class="dashboard_paginate">
                    <%= will_paginate @activities%>
                </div>
            </div>
        </div>
    </div>
</div>


app/views/users/edit.html.erb
<div class="col-6 mx-auto">
    <div class="category_top"> 
        <h1 class= "text-center m-4">Settings</h1>
    </div>
	<%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="category_top">
    <h1>Users</h1>
</div> 

<div class="paginate">
    <%= will_paginate %>
</div>

<div class= "row bottom">
    <% @users.each do |user| %>
        <div class="col-6">
            <div class="media mb-3">
                <%= gravatar_for(user) %>
                <div class="media-body">
                    <h5 class="pt-2 font-weight-bold"><%= link_to user.name, user %> </h5>
                </div>     
            </div>
        </div>
    <% end %>
</div>

app/views/users/new.html.erb
<div class="col-6 costom-margin mx-auto">
    <h1 class= "text-center m-4">Sign up</h1>
    <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="row mt-4">
    <div class="col-3 text-center">
       <div class="media-body userprofile ml-3">
        	<%= gravatar_for @user %>
        	<h4><%= @user.name%></h4>
        	<h5><%= @user.email%></h5>
    	</div>

           <div class="col-12 text center">
        <div class="row">
            <div class="col-6">
                <h3><%=@user.active_relationships.count%></h3>
                following
            </div>
            <div class="col-6">
               <h3><%=@user.passive_relationships.count%></h3>
                followers
            </div>
        <div class="form-group">
            <% if current_user != @user %>
                <% unless current_user.following?(@user)%>
                    <%= form_for(current_user.active_relationships.build) do |f| %>
                        <div><%= hidden_field_tag :followed_id,@user.id %></div>
                        <%= f.submit "Follow", class:"btn btn-outline-primary btn-lg mt-2 btn-follow"%>
            		<% end %>
            <% else %>
                    <%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
                        html:{method: :delete}) do |f|%>
                        <%= f.submit "Unfollow",class: "btn btn-danger btn-lg mt-2 btn-follow"%>
                    <% end %>
                <% end %>
            <% end %>
             <%= link_to "admin",admin_home_path, class: "btn btn-outline-info btn-lg mt-2 btn-follow" %>
        </div>
        </div>
    </div>

    </div>
    <div class="col-9">
       <div class="card activity feed_paginate">
            <div class="card-header">
                Activities
            </div>
            <div class="card-body">
                <%= render 'shared/feed' %>
                <div class="dashboard_paginate">
                    <%= will_paginate @activities%>
                </div>
            </div>
        </div>
    </div>
</div>