config/routes.rb
Rails.application.routes.draw do
  root 'staticpages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  delete '/logout', to:'sessions#destroy' 
  resources :sessions
  resources :users
  resources :relationships,only:[:create,:destroy]
  resources :categories

  resources :lessons,only:[:create, :show] do
    resources :answers
  end
  
  namespace :admin do
    get'/home', to:'users#home'
    resources :users
    resources :categories do
      resources :words
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :action,polymorphic: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :lesson
  belongs_to :word
  belongs_to :choice
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  has_many :words, dependent: :destroy
  has_many :lessons,dependent: :destroy
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :word
  has_many :answer,dependent: :destroy
  validates :content, presence: true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :words, through: :answers
  has_many :choices, through: :answers
  has_one :activity,as: :action,dependent: :destroy


  def lesson_results
    choices.where(isCorrect: true).count
  end

  def next_word
    (category.words - words).first
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower ,class_name: "User"
  belongs_to :followed ,class_name: "User"
  validates :follower_id,presence: true
  validates :followed_id,presence: true
  has_one :activity,as: :action,dependent: :destroy

  after_create :relationship_activity

  private
  def relationship_activity
    create_activity(user: follower)
  end
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  #filter method to transform email to small case before saving to db 
  before_save {email.downcase!}

  validates :name, presence: true, length: {maximum:50 }
  # REGEX = Reguuler Expression
  # To validate correct email structure
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum:50 },
                                    format: {with: EMAIL_REGEX},
                                    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password,length:{minimum:6}, allow_nil:true

  has_many :active_relationships,class_name:"Relationship",
  foreign_key:"follower_id",
  dependent: :destroy

  has_many :passive_relationships,class_name:"Relationship",
  foreign_key:"followed_id",
  dependent: :destroy

  has_many :following,through: :active_relationships, source: :followed
  has_many :followers,through: :active_relationships, source: :follower
  has_many :lessons,dependent: :destroy
  has_many :activities,dependent: :destroy
  has_many :categories, through: :lessons

  #follow a user
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end
  #Unfollows a user
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  #returns ture if the current user is following the other user.
  def following? (other_user)
    following.include?(other_user)
  end

  def lesson_taken(category_id)
    lesson = lessons.find_by(category_id: category_id)
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :choices, dependent: :destroy
  has_many :answer,dependent: :destroy
  validate :has_one_correct_answer
  accepts_nested_attributes_for :choices
  validates :choices, presence: true
  validates :content, presence: true
  validate :has_unique_choice

  def has_one_correct_answer
    if choices.select{|choice| choice.isCorrect? }.count !=1
      return errors.add :base,"Must have one correct choice"
    end
  end

  def has_unique_choice
    @uniq_choices = choices.uniq{|choice| choice.content}.length
    if @uniq_choices < choices.length
      return errors.add :base,"Must have uniqe choice"
    end
  end

  def correct_answer
    choices.find_by(isCorrect:true).try(:content)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
      session[:user_id] = user.id
  end

    # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    #Generate hex token
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name)
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <%= link_to 'E-learning','#', class: "navbar-brand" %>
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'E-learning','#', class: "navbar-brand" %>
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <%= link_to "Home", root_path, class:"nav-link"%>
            </li>

            <% if logged_in? %>
                <li class="nav-item">
                    <%= link_to "Lessons",categories_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Users",users_path, class: "nav-link" %>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= current_user.name %>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <%= link_to"profile",current_user,class:"dropdown-item"%>
                        <%= link_to "Settings",edit_user_path(current_user),class:"dropdown-item"%>
                        <div class="dropdown-divider"></div>
                        <%= link_to "Logout",logout_path, method: :delete, class: "dropdown-item"%>
                    </div>
                </li>
            <% else %>
                <li class="nav-item">
                    <%= link_to "Signup",signup_path,class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Login",login_path, class: "nav-link" %>
                </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>TaigaElearning</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <%= render 'layouts/header'%>
        <div class="container">
            <%= yield %>
        </div>
        <%= render 'layouts/footer'%>
    </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count,"error")%>
    </div>

    <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
    <hr>
<% end %>

app/views/shared/_feed.html.erb
<% if @activities.any? %>

<% else %>
    <h3 class="text-muted text-center">Nothing to show</h3>
<% end %>

<% @activities.each do |activity| %>
    <% if activity.action_type == "Lesson" %>
        <div class="media setting_activity">
            <% if activity.user == current_user %>
                <%= gravatar_for(current_user) %>
            <% else %>
                <%= gravatar_for(activity.user) %>
            <% end %>
            <div class="media-body">  
                <%= link_to_if activity.user == current_user, "You",user_path(current_user) do
                link_to activity.user.name, user_path(activity.user.id) end %> learned
                <%= activity.action.lesson_results %> of
                <%= activity.action.words.size %> in
                <%= link_to activity.action.category.title, "#" %>
                <div>
                    <small class="text-muted"><%= time_ago_in_words(activity.created_at) %> </small>
                </div>
            </div>
        </div>
    <% else %>
        <div class="media">
            <div class="media setting_activity">
                <% if activity.user == current_user %>
                    <%= gravatar_for(current_user) %>
                <% else %>
                    <%= gravatar_for(activity.user) %>
                <% end %>
                <div class="media-body">
                    <%= link_to_if activity.user == current_user, "You", user_path(current_user) do 
                    link_to activity.user.name, user_path(activity.user.id) end %> followed
                    <%= link_to activity.action.followed.name,activity.action.followed %>
                    <div>
                        <small class="text-muted"><%= time_ago_in_words(activity.created_at) %></small>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
<% end %>

    